name: ESP32-S3 CAN firmware

on:
  push:
    paths:
      - 'ports/esp32/**'
      - '.github/workflows/ports_esp32.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Setup ESP-IDF
      uses: ./.github/actions/setup_esp32
      with:
        idf_ver: 'v5.5.2'
        ccache_key: 'esp32s3'

    - name: Build MicroPython for ESP32-S3
      run: |
        source $IDF_PATH/export.sh
        make -C ports/esp32 BOARD=ESP32_GENERIC_S3

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-ESP32-S3
        path: |
          ports/esp32/build-ESP32_GENERIC_S3/bootloader/bootloader.bin
          ports/esp32/build-ESP32_GENERIC_S3/partition_table/partition-table.bin
          ports/esp32/build-ESP32_GENERIC_S3/micropython.bin
